package org.example.beyondubackend.domain.university.implement

enum class Nation(val displayName: String) {
    GUATEMALA("과테말라"),
    GREECE("그리스"),
    NETHERLANDS("네덜란드"),
    NEW_ZEALAND("뉴질랜드"),
    TAIWAN("대만"),
    DENMARK("덴마크"),
    DOMINICAN_REPUBLIC("도미니카공화국"),
    GERMANY("독일"),
    LATVIA("라트비아"),
    RUSSIA("러시아"),
    ROMANIA("루마니아"),
    LITHUANIA("리투아니아"),
    MALAYSIA("말레이시아"),
    MEXICO("멕시코"),
    MONGOLIA("몽골"),
    USA("미국"),
    MYANMAR("미얀마"),
    BANGLADESH("방글라데시"),
    VIETNAM("베트남"),
    BELGIUM("벨기에"),
    BRAZIL("브라질"),
    SWEDEN("스웨덴"),
    SWITZERLAND("스위스"),
    SPAIN("스페인"),
    SINGAPORE("싱가포르"),
    ARGENTINA("아르헨티나"),
    IRELAND("아일랜드"),
    AZERBAIJAN("아제르바이잔"),
    ESTONIA("에스토니아"),
    ECUADOR("에콰도르"),
    UK("영국"),
    AUSTRIA("오스트리아"),
    URUGUAY("우루과이"),
    UZBEKISTAN("우즈베키스탄"),
    UKRAINE("우크라이나"),
    ITALY("이탈리아"),
    INDIA("인도"),
    INDONESIA("인도네시아"),
    JAPAN("일본"),
    CHINA("중국"),
    CZECH("체코"),
    CHILE("칠레"),
    KAZAKHSTAN("카자흐스탄"),
    CANADA("캐나다"),
    COLOMBIA("콜롬비아"),
    CROATIA("크로아티아"),
    KYRGYZSTAN("키르기스스탄"),
    THAILAND("태국"),
    TUNISIA("튀니지"),
    TURKEY("튀르키예(터키)"),
    PERU("페루"),
    PORTUGAL("포르투갈"),
    POLAND("폴란드"),
    FRANCE("프랑스"),
    FINLAND("핀란드"),
    PHILIPPINES("필리핀"),
    HUNGARY("헝가리"),
    AUSTRALIA("호주"),
    HONG_KONG("홍콩");

    companion object {
        fun fromDisplayName(name: String): Nation? = entries.find { it.displayName == name }
    }
}
